import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, beforeEach, expect, it } from "vitest";

let db: PGlite;
const migration = readFileSync(
	new URL(
		"../../supabase/migrations/202610080008_evaluation_period_management.sql",
		import.meta.url,
	),
	"utf8",
);
const uid = (id: number) => `00000000-0000-0000-0000-${String(id).padStart(12, "0")}`;
/** 1: Admin, 2: Reviewer, 3: Employee */
const login = async (id: number) => {
	await db.query("select set_config('request.jwt.claim.sub', $1, false)", [uid(id)]);
};
const activate = async (periodId: number) =>
	(
		await db.query<{ switched: boolean }>(
			"select public.activate_evaluation_period($1) as switched",
			[periodId],
		)
	).rows[0].switched;
const active = async () =>
	(
		await db.query<{ id: number }>(
			"select id from public.evaluation_periods where is_active order by id",
		)
	).rows.map((row) => Number(row.id));
const denied = { code: "42501" };
const closed = { code: "23514", message: "締められた評価期間の評価シートは変更できません。" };
const finalizeActiveSheet = () =>
	db.query("update public.evaluation_sheets set status = 'finalized' where id = 200");

beforeAll(async () => {
	db = await PGlite.create();
	await db.exec(`
		create role anon; create role authenticated; create schema auth;
		create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
		create table public.roles (id integer primary key, role_name text);
		create table public.employees (id integer primary key, user_id uuid, role_id integer);
		insert into public.roles values (1, 'Admin'), (2, 'Reviewer'), (3, 'Employee');
		insert into public.employees select id, ('00000000-0000-0000-0000-' || lpad(id::text, 12, '0'))::uuid, id from generate_series(1, 3) id;
		-- 本番と同じ: 読み取りだけのポリシー、既定で実施中、シートは期間の削除に連鎖する
		create table public.evaluation_periods (id bigint generated by default as identity primary key, period_name text not null unique, start_date date not null, end_date date not null, is_active boolean default true);
		alter table public.evaluation_periods enable row level security;
		create policy "periods select" on public.evaluation_periods for select using (true);
		create table public.evaluation_sheets (id bigint primary key, period_id bigint not null references public.evaluation_periods(id) on delete cascade, status text default 'draft');
		create table public.milestones (id bigint primary key, sheet_id bigint, first_score integer default 0);
		create table public.common_evaluation_results (id bigint primary key, sheet_id bigint, first_score integer default 0);
		grant all on public.evaluation_periods, public.evaluation_sheets, public.milestones, public.common_evaluation_results to anon, authenticated;
		grant select on public.employees, public.roles to authenticated;
		insert into public.evaluation_periods values (1, '25期', '2025-03-01', '2026-02-28', null), (2, '26期', '2026-03-01', '2027-02-28', true);
		select setval(pg_get_serial_sequence('public.evaluation_periods', 'id'), 10);
		insert into public.evaluation_sheets values (100, 1, 'finalized'), (101, 1, 'finalized'), (200, 2, 'draft');
		insert into public.milestones values (11, 100), (21, 200);
		insert into public.common_evaluation_results values (31, 100), (41, 200);
	`);
	await db.exec(migration);
	await db.exec(migration);
}, 30_000);
beforeEach(async () => {
	// 準備ではトリガーを止めて、締めた期間のシートも元の値に戻す
	await db.exec(`reset role; set session_replication_role = replica;
		delete from public.evaluation_periods where id > 2;
		update public.evaluation_periods set is_active = false;
		update public.evaluation_periods set is_active = true, period_name = '26期' where id = 2;
		delete from public.evaluation_sheets where id > 200;
		update public.evaluation_sheets set status = case id when 200 then 'draft' else 'finalized' end;
		update public.milestones set first_score = 0;
		set session_replication_role = origin; set role authenticated;`);
	await login(1);
});
afterAll(async () => {
	await db?.close();
});

it("keeps exactly one active period, switched only by closing, and lets the switch be undone", async () => {
	// 未設定(null)だった期間は、締めた期間として扱う
	expect(await active()).toEqual([2]);
	await expect(
		db.query("update public.evaluation_periods set is_active = true where id = 1"),
	).rejects.toMatchObject(denied);

	await finalizeActiveSheet();
	expect(await activate(1)).toBe(true);
	expect(await active()).toEqual([1]);
	// 間違えたら、元の期間をもう一度有効にすれば戻る
	expect(await activate(2)).toBe(true);
	expect(await activate(2)).toBe(true);
	expect(await active()).toEqual([2]);
	expect(await activate(999)).toBe(false);
	expect(await active()).toEqual([2]);

	for (const other of [2, 3]) {
		await login(other);
		await expect(activate(1)).rejects.toMatchObject(denied);
	}
	await db.exec("reset role; set role anon");
	await expect(activate(1)).rejects.toMatchObject(denied);
	// DB の管理者でも、実施中の期間を 2 つにはできない
	await db.exec("reset role");
	await expect(
		db.exec("update public.evaluation_periods set is_active = true where id = 1"),
	).rejects.toMatchObject({ code: "23505" });
	expect(await active()).toEqual([2]);
});

it.each(["draft", "submitted", "first_evaluated"])(
	"refuses to close a period that still has a %s sheet",
	async (status) => {
		await db.query("update public.evaluation_sheets set status = $1 where id = 200", [status]);
		await expect(activate(1)).rejects.toMatchObject({
			code: "23514",
			message: "未確定の評価シートが残っているため、評価期間を締められません。",
		});
		expect(await active()).toEqual([2]);
		// 実施中の期間をもう一度指定するだけなら、何も締めないので通る
		expect(await activate(2)).toBe(true);
		await finalizeActiveSheet();
		expect(await activate(1)).toBe(true);
		expect(await active()).toEqual([1]);
	},
);

it("lets only an Admin add, edit and delete periods, and a new period never starts active", async () => {
	const added = await db.query<{ id: number; is_active: boolean }>(
		"insert into public.evaluation_periods (period_name, start_date, end_date) values ('27期', '2027-03-01', '2028-02-29') returning id, is_active",
	);
	expect(added.rows[0].is_active).toBe(false);
	const id = added.rows[0].id;
	await expect(
		db.query(
			"insert into public.evaluation_periods (period_name, start_date, end_date, is_active) values ('28期', '2028-03-01', '2029-02-28', true)",
		),
	).rejects.toMatchObject(denied);
	await expect(
		db.query(
			"insert into public.evaluation_periods (period_name, start_date, end_date) values ('26期', '2030-03-01', '2031-02-28')",
		),
	).rejects.toMatchObject({ code: "23505" });
	await db.query("update public.evaluation_periods set period_name = '27期(改)' where id = $1", [
		id,
	]);
	await expect(
		db.query("update public.evaluation_periods set end_date = '2020-01-01' where id = $1", [id]),
	).rejects.toMatchObject({ code: "23514" });

	for (const other of [2, 3]) {
		await login(other);
		await expect(
			db.query(
				"insert into public.evaluation_periods (period_name, start_date, end_date) values ('29期', '2029-03-01', '2030-02-28')",
			),
		).rejects.toMatchObject(denied);
		expect(
			(
				await db.query(
					"update public.evaluation_periods set period_name = '勝手に変更' where id = $1 returning id",
					[id],
				)
			).rows,
		).toEqual([]);
		expect(
			(await db.query("delete from public.evaluation_periods where id = $1 returning id", [id]))
				.rows,
		).toEqual([]);
	}

	await login(1);
	// 実施中の期間と、評価シートのある期間は消せない(シートは期間の削除に連鎖して消えてしまう)
	await expect(db.query("delete from public.evaluation_periods where id = 2")).rejects.toThrow(
		"実施中の評価期間は削除できません。",
	);
	await expect(db.query("delete from public.evaluation_periods where id = 1")).rejects.toThrow(
		"評価シートのある評価期間は削除できません。",
	);
	expect((await db.query("select id from public.evaluation_sheets")).rows).toHaveLength(3);
	expect(
		(await db.query("delete from public.evaluation_periods where id = $1 returning id", [id])).rows,
	).toHaveLength(1);
});

it("freezes the sheets, goals and common results of a closed period, also for direct API calls", async () => {
	await login(3);
	const changes = (sheetId: number, childId: number) => [
		`update public.evaluation_sheets set status = 'draft' where id = ${sheetId}`,
		`delete from public.evaluation_sheets where id = ${sheetId}`,
		`update public.milestones set first_score = 4 where sheet_id = ${sheetId}`,
		`insert into public.milestones (id, sheet_id) values (${childId}, ${sheetId})`,
		`delete from public.milestones where sheet_id = ${sheetId}`,
		`update public.common_evaluation_results set first_score = 4 where sheet_id = ${sheetId}`,
		`insert into public.common_evaluation_results (id, sheet_id) values (${childId}, ${sheetId})`,
		`delete from public.common_evaluation_results where sheet_id = ${sheetId}`,
	];
	for (const change of changes(100, 901)) {
		await expect(db.query(change), change).rejects.toMatchObject(closed);
	}
	// 締めた期間には、シートを新しく作ることも、実施中の期間から移すこともできない
	await expect(
		db.query("insert into public.evaluation_sheets (id, period_id) values (102, 1)"),
	).rejects.toMatchObject(closed);
	await expect(
		db.query("update public.evaluation_sheets set period_id = 1 where id = 200"),
	).rejects.toMatchObject(closed);
	await db.query("update public.milestones set first_score = 3 where sheet_id = 200");
	await finalizeActiveSheet();

	// 期間を切り替えると、編集できる期間も入れ替わる
	await login(1);
	await activate(1);
	await login(3);
	await db.query("update public.milestones set first_score = 2 where sheet_id = 100");
	await db.query("insert into public.evaluation_sheets (id, period_id) values (201, 1)");
	await expect(
		db.query("update public.milestones set first_score = 1 where sheet_id = 200"),
	).rejects.toMatchObject(closed);
	expect(
		(await db.query("select sheet_id, first_score from public.milestones order by id")).rows,
	).toEqual([
		{ sheet_id: 100, first_score: 2 },
		{ sheet_id: 200, first_score: 3 },
	]);
});

it("tells only an Admin how many sheets of a period are in each status", async () => {
	const counts = async (periodId: number) =>
		(
			await db.query<{ counts: Record<string, number> }>(
				"select public.get_evaluation_period_sheet_counts($1) as counts",
				[periodId],
			)
		).rows[0].counts;
	expect(await counts(1)).toEqual({ finalized: 2 });
	expect(await counts(2)).toEqual({ draft: 1 });
	expect(await counts(999)).toEqual({});
	for (const other of [2, 3]) {
		await login(other);
		await expect(counts(1)).rejects.toMatchObject(denied);
	}
	await db.exec("reset role; set role anon");
	await expect(counts(1)).rejects.toMatchObject(denied);
});
