import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, expect, it } from "vitest";

let db: PGlite;
const migration = readFileSync(
	new URL("../../supabase/migrations/202610080011_unique_rows.sql", import.meta.url),
	"utf8",
);
// 本番と同じ: evaluation_sheets と common_evaluation_results には既に制約があり、milestones にはない
const schema = `
	create table public.evaluation_sheets (id bigint generated by default as identity primary key, period_id bigint, employee_id bigint,
		constraint evaluation_sheets_period_id_employee_id_key unique (period_id, employee_id));
	create table public.milestones (id bigint generated by default as identity primary key, sheet_id bigint, goal_number integer, challenge_goal text);
	create table public.common_evaluation_results (id bigint generated by default as identity primary key, sheet_id bigint, item_id bigint, first_score integer, second_score integer,
		constraint common_evaluation_results_sheet_id_item_id_key unique (sheet_id, item_id));
`;

beforeAll(async () => {
	db = await PGlite.create();
	await db.exec(schema);
	await db.exec(migration);
	await db.exec(migration);
}, 30_000);
afterAll(async () => {
	await db?.close();
});

it("adds the missing key once and leaves the existing ones alone", async () => {
	const keys = await db.query<{ conname: string; columns: string }>(
		"select conname, pg_get_constraintdef(oid) as columns from pg_constraint where contype = 'u' and connamespace = 'public'::regnamespace order by conname",
	);
	expect(keys.rows).toEqual([
		{
			conname: "common_evaluation_results_sheet_id_item_id_key",
			columns: "UNIQUE (sheet_id, item_id)",
		},
		{
			conname: "evaluation_sheets_period_id_employee_id_key",
			columns: "UNIQUE (period_id, employee_id)",
		},
		{ conname: "milestones_sheet_id_goal_number_key", columns: "UNIQUE (sheet_id, goal_number)" },
	]);
});

it("saves by key: the same goal or result is updated, never added twice", async () => {
	const saveGoal = (text: string) =>
		db.query(
			"insert into public.milestones (sheet_id, goal_number, challenge_goal) values (100, 1, $1) on conflict (sheet_id, goal_number) do update set challenge_goal = excluded.challenge_goal",
			[text],
		);
	await saveGoal("最初の目標");
	await saveGoal("書き直した目標");
	expect(
		(await db.query("select sheet_id, goal_number, challenge_goal from public.milestones")).rows,
	).toEqual([{ sheet_id: 100, goal_number: 1, challenge_goal: "書き直した目標" }]);
	await expect(
		db.query("insert into public.milestones (sheet_id, goal_number) values (100, 1)"),
	).rejects.toMatchObject({ code: "23505" });

	// 一次評価者の保存が、二次評価の点数を消さない(渡した列だけが書き換わる)
	await db.exec(
		"insert into public.common_evaluation_results (sheet_id, item_id, second_score) values (100, 31, 4)",
	);
	await db.exec(
		"insert into public.common_evaluation_results (sheet_id, item_id, first_score) values (100, 31, 3) on conflict (sheet_id, item_id) do update set first_score = excluded.first_score",
	);
	expect(
		(await db.query("select first_score, second_score from public.common_evaluation_results")).rows,
	).toEqual([{ first_score: 3, second_score: 4 }]);
	await expect(
		db.query(
			"insert into public.evaluation_sheets (period_id, employee_id) values (10, 1), (10, 1)",
		),
	).rejects.toMatchObject({ code: "23505" });
});

it("refuses to add the key while duplicate goals exist, instead of deleting anything", async () => {
	const other = await PGlite.create();
	try {
		await other.exec(schema);
		await other.exec(
			"insert into public.milestones (sheet_id, goal_number) values (100, 1), (100, 1)",
		);
		await expect(other.exec(migration)).rejects.toMatchObject({ code: "23505" });
		await other.exec("rollback");
		expect((await other.query("select id from public.milestones")).rows).toHaveLength(2);
	} finally {
		await other.close();
	}
}, 30_000);
